@startuml
'********************************* CLASS *********************************'
class GameMenu {
-newGame : Button
-tutorials : Button
-highScore : Button
-settings : Button
-credits : Button
}

class Gamer {
-name
}

class NPC

class Maps{
-size : ArrayList
}
class Maps_1{
-Path path_1
-Path path_2
}
class Maps_n{
-Path path_1
-Path path_2
}

class Button{
-size : ArrayList
-color : String
}

interface Shape{
setShape()
}
interface Speed{
setSpeed()
}
interface health{
setHealth()
}
class Enemy{
}
class Enemy_1{
-shape : Shape
-hp  : Health
-speed : Speed
}
class Enemy_n{
-shape : Shape
-hp : Health
-speed : Speed
}
class Allied
class Allied_1{
-shape : Shape
-hp : Health
-speed : Speed
}
class Allied_n{
-shape : Shape
-hp : Health
-speed : Speed
}

interface Damage{
setDamage()
}
interface Range{
setRange()
}
interface FireRate{
setFireRate()
}
class Tower
class Tower_1{
-damage : Damage
-range : Range
-rate : FireRate
}
class Tower_n{
-damage : Damage
-range : Range
-rate : FireRate
}

class Path
'********************************* BOUNDS *********************************'

Tower<--Tower_1
Tower<--Tower_n

Enemy<--Enemy_1
Enemy<--Enemy_n

Allied<--Allied_1
Allied<--Allied_n

NPC<--Enemy
NPC<--Allied

Maps<--Maps_1
Maps<--Maps_n
@enduml